#!/usr/bin/env ruby
# Usage: toolbox backup-db 
# Summary: backups the  

require_relative './shared-lib'
root_dir = File.dirname(__FILE__)

config = "#{root_dir}/configs/ssh_config"
backup_command = 'mysqldump '

backup = SSH.command_builder(config, 'db', 'mysqldump -u root -proot freedom35 > ~/prod.sql')
Command.run(backup)

gzip = SSH.command_builder(config, 'db', 'gzip prod.sql')
Command.run(gzip)

scp = SSH.scp_from(config, 'db', 'prod.sql.gz')
Command.run(scp)

rm = SSH.command_builder(config, 'db', 'rm ~/prod.sql.gz')
Command.run(rm)
